/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mitología;

import java.awt.CardLayout;

/**
 *
 * @author a22iagorg
 */
public class InterfazF extends javax.swing.JFrame {

    /**
     * Creates new form prueba
     */
    public InterfazF() {
        initComponents();
    }
    
       private void cambiarCard(String card) {
        CardLayout cardL = (CardLayout)panelPrincipal.getLayout();
        cardL.show(panelPrincipal, card);
    }
    
    
    
    
     DAO mitologia = new DAO("localhost", 3306, "mitologiabd", "root", "root");
    
    public void mostrarDiosesSeleccionados() {
        String diosesSeleccionados="";
        boolean griegaSeleccionada = Griega.isSelected();
        boolean egipciaSeleccionada = Egipcia.isSelected();
        boolean nórdicaSeleccionada = Nórdica.isSelected();
        boolean japonesaSeleccionada = Japonesa.isSelected();
        boolean mayaSeleccionada = Maya.isSelected();
        boolean hindúSeleccionada = Hindú.isSelected();
        boolean chinaSeleccionada = China.isSelected();
        boolean babilónicaSeleccionada = Babilónica.isSelected();
        boolean yorubaSeleccionada = Yoruba.isSelected();
        boolean eslavaSeleccionada = Eslava.isSelected();
        boolean polinesiaSeleccionada = Polinesia.isSelected();
        boolean celtaSeleccionada = Celta.isSelected();
        
        
     diosesSeleccionados = mitologia.getDiosesSeleccionadosMitologias(griegaSeleccionada,
             egipciaSeleccionada, nórdicaSeleccionada, japonesaSeleccionada, mayaSeleccionada, 
             hindúSeleccionada, chinaSeleccionada, babilónicaSeleccionada, 
             yorubaSeleccionada, eslavaSeleccionada, polinesiaSeleccionada, celtaSeleccionada);

  
    textoDioses.setText(diosesSeleccionados);

    }
    
    
    
    
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        PanelInicio = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        PanelMitologia = new javax.swing.JPanel();
        tituloMitos = new javax.swing.JLabel();
        Nórdica = new javax.swing.JCheckBox();
        textoDioses = new javax.swing.JLabel();
        Japonesa = new javax.swing.JCheckBox();
        textoMitos = new javax.swing.JLabel();
        Maya = new javax.swing.JCheckBox();
        Hindú = new javax.swing.JCheckBox();
        botonParaQueAparezcan = new javax.swing.JButton();
        China = new javax.swing.JCheckBox();
        Babilónica = new javax.swing.JCheckBox();
        Eslava = new javax.swing.JCheckBox();
        Griega = new javax.swing.JCheckBox();
        Polinesia = new javax.swing.JCheckBox();
        Yoruba = new javax.swing.JCheckBox();
        Celta = new javax.swing.JCheckBox();
        tituloDioses = new javax.swing.JLabel();
        Egipcia = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.CardLayout());

        jButton1.setText("Ir panel Mitologia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelInicioLayout = new javax.swing.GroupLayout(PanelInicio);
        PanelInicio.setLayout(PanelInicioLayout);
        PanelInicioLayout.setHorizontalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButton1)
                .addContainerGap(541, Short.MAX_VALUE))
        );
        PanelInicioLayout.setVerticalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap(632, Short.MAX_VALUE))
        );

        panelPrincipal.add(PanelInicio, "card2");

        tituloMitos.setText("Mitos");

        Nórdica.setText("Japonesa");
        Nórdica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NórdicaActionPerformed(evt);
            }
        });

        textoDioses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Japonesa.setText("Nórdica");
        Japonesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JaponesaActionPerformed(evt);
            }
        });

        textoMitos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Maya.setText("Hindú");

        Hindú.setText("Maya");

        botonParaQueAparezcan.setText("Buscar");
        botonParaQueAparezcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonParaQueAparezcanActionPerformed(evt);
            }
        });

        China.setText("Babilónica");

        Babilónica.setText("Eslava");
        Babilónica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BabilónicaActionPerformed(evt);
            }
        });

        Eslava.setText("Celta");

        Griega.setText("Griega");
        Griega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GriegaActionPerformed(evt);
            }
        });

        Polinesia.setText("Polinesia");

        Yoruba.setText("Yoruba");

        Celta.setText("China");

        tituloDioses.setText("Dioses");

        Egipcia.setText("Egipcia");

        jButton2.setText("Volver a panel inicial");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMitologiaLayout = new javax.swing.GroupLayout(PanelMitologia);
        PanelMitologia.setLayout(PanelMitologiaLayout);
        PanelMitologiaLayout.setHorizontalGroup(
            PanelMitologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMitologiaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanelMitologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMitologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(China)
                        .addGroup(PanelMitologiaLayout.createSequentialGroup()
                            .addGroup(PanelMitologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Hindú)
                                .addComponent(Nórdica)
                                .addComponent(Maya))
                            .addGap(6, 6, 6))
                        .addComponent(Celta, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Yoruba, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Babilónica, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Polinesia, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Eslava, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(PanelMitologiaLayout.createSequentialGroup()
                        .addGroup(PanelMitologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Japonesa)
                            .addComponent(Egipcia)
                            .addComponent(Griega)
                            .addComponent(botonParaQueAparezcan))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(PanelMitologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMitologiaLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(textoDioses, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(textoMitos, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMitologiaLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(tituloDioses)
                        .addGap(234, 234, 234)
                        .addComponent(tituloMitos)))
                .addGap(26, 26, 26))
            .addGroup(PanelMitologiaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMitologiaLayout.setVerticalGroup(
            PanelMitologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMitologiaLayout.createSequentialGroup()
                .addGroup(PanelMitologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMitologiaLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(PanelMitologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloDioses)
                            .addComponent(tituloMitos))
                        .addGap(39, 39, 39)
                        .addComponent(textoMitos, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMitologiaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addGap(34, 34, 34)
                        .addGroup(PanelMitologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelMitologiaLayout.createSequentialGroup()
                                .addComponent(Griega)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Egipcia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Japonesa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nórdica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Hindú)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Maya)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Celta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(China)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Yoruba)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Babilónica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Polinesia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Eslava)
                                .addGap(47, 47, 47)
                                .addComponent(botonParaQueAparezcan))
                            .addComponent(textoDioses, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        panelPrincipal.add(PanelMitologia, "card3");

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cambiarCard("card3");        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NórdicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NórdicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NórdicaActionPerformed

    private void JaponesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JaponesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JaponesaActionPerformed

    private void botonParaQueAparezcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonParaQueAparezcanActionPerformed
        
        mostrarDiosesSeleccionados();
        // TODO add your handling code here:
    }//GEN-LAST:event_botonParaQueAparezcanActionPerformed

    private void BabilónicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BabilónicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BabilónicaActionPerformed

    private void GriegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GriegaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GriegaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cambiarCard("card2");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Babilónica;
    private javax.swing.JCheckBox Celta;
    private javax.swing.JCheckBox China;
    private javax.swing.JCheckBox Egipcia;
    private javax.swing.JCheckBox Eslava;
    private javax.swing.JCheckBox Griega;
    private javax.swing.JCheckBox Hindú;
    private javax.swing.JCheckBox Japonesa;
    private javax.swing.JCheckBox Maya;
    private javax.swing.JCheckBox Nórdica;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JPanel PanelMitologia;
    private javax.swing.JCheckBox Polinesia;
    private javax.swing.JCheckBox Yoruba;
    private javax.swing.JButton botonParaQueAparezcan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel textoDioses;
    private javax.swing.JLabel textoMitos;
    private javax.swing.JLabel tituloDioses;
    private javax.swing.JLabel tituloMitos;
    // End of variables declaration//GEN-END:variables
}
